version: '3'

services:
  ghost:
    image: ghost:1-alpine
    ports:
      - 2368:2368
    restart: always
    depends_on:
      - "db"
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: password
      database__connection__database: ghost
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password